project:
  type: book
  output-dir: docs

book:
  title: "Cristales de Tiempo de Floquet"
  author: "Mario sebastián Torres Rubio"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - teoria.qmd
    - metodos.qmd
    - simulaciones.qmd 
    - summary.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



